### ISSUE TITLE
Implement middleware

### ISSUE THREAD

**Issue by BasMasking** [MaskingTechnology/jitar#1]
We need to add middleware support

**Comment by petermasking** [comment]
I've created a little design for the middleware implementation. In the design I've used an auth flow as example to get a grip on the requirements. It shows that we need to hook into incoming and outgoing requests on the gateway and node (note that the browser is also a node).

![Middleware design](https://user-images.githubusercontent.com/108156553/208187782-8707d1a4-dafd-4041-b445-06cc1a719895.png)

**Comment by BasMasking** [comment]
Implementation details
- remote implementations only forward all headers (both incoming and outgoing)
- only required for RPC calls
