### ISSUE TITLE
Create production bundles

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/jitar#232]
Currently when importing as dependency, all components are loaded as separate files. This works well when developing Jitar, but is very inefficient in production. Therefore we need to create optimized production bundles:

1. lib.js (containing everything, including sub-packages)
2. client.js (containing only what's needed by the web-client)

Both bundles already have been defined in the jitar package, and only have to be rolled up.

We might need to add an additional bundle for the errors that can be separately loaded from any end at deserialization.

**Comment by BasMasking** [comment]
@petermasking this can be closed right?

**Comment by petermasking** [comment]
Yes, this is done in #249
