### ISSUE TITLE
Middleware per procedure

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/jitar#237]
Currently we can add middleware to a runtime service (gateway, node, proxy) that is applied to each procedure request. Next we want to be able to specify what middleware to apply to what procedure.

For this we need to change the registration of middleware a bit, by naming them in the starter file:

```ts
startServer(moduleImporter).then(server =>
{
    // Before
    server.addMiddleware(new AuthMiddleware());

    // After
    server.registerMiddleware('auth', new AuthMiddleware());
});
```

We also need to extend the segment configuration:

```json
{
    "./account/update.js": {
        "default": {
            "access": "public",
            "middlewares": ["auth"]
        }
    }
}
```

To make it easier to add the middleware to a group of procedures, we want to also be able to configure them on module and segment level. An example configuration could look like this:

```json
{
    "middlewares": ["logging"],
    "modules": {
        "./account/update.js": {
            "middlewares": ["auth"]
            "procedures": {
                "default": {
                    "access": "public",
                    "middlewares": ["notify"]
                }
            }
        }
    }
}
```

**Note** that the implementation will break existing segment configurations because additional configuration levels have been added. We can prevent this by using __special__ keys beginning with a specific specifier (e.g. ~) like this:

```json
{
    "~middlewares": ["logging"],
    "./account/update.js": {
        "~middlewares": ["auth"]
        "default": {
            "access": "public",
            "middlewares": ["notify"]
        }
    }
}
```

This isn't the most beautiful option, but it doesn't break existing configurations, is easier and quicker to configure. We need to decide what configuration style to use before picking up this issue.

Next, we want to make the middleware configurable from the segment file to prevent registering a lot of specific in the starter file like this:

```ts
startServer(moduleImporter).then(server =>
{
    // Avoid this situation
    server.registerMiddleware('auth-admin-department-x', new AuthMiddleware('admin', 'department-x'));
    server.registerMiddleware('auth-admin-department-y', new AuthMiddleware('admin', 'department-y'));
    server.registerMiddleware('auth-manager-department-x', new AuthMiddleware('manager', 'department-x'));
    server.registerMiddleware('auth-manager-department-y', new AuthMiddleware('manager', 'department-y'));
    server.registerMiddleware('auth-customer-type-a', new AuthMiddleware('customer', 'type-a'));
    /* ... */
});
```

In the desired situation we only register the middleware once, and provide the construction arguments from the configuration like this:

```json
{
    "./some/module.js": {
        "doMagic": {
            "access": "public",
            "middlewares": {
                "auth": { "role": "manager", "scope": "department-x" }
            }
        }
    }
}
```

For this we need to figure out how we want to create new middleware instances from the configuration. The easiest is to only register the middleware class in the starter file like this:

```ts
startServer(moduleImporter).then(server =>
{
    // Before (register an instance)
    server.registerMiddleware('auth', new AuthMiddleware());

    // After (register the class)
    server.registerMiddleware('auth', AuthMiddleware);
});
```

The `AuthMiddleware` should specify the configured properties as constructor parameters:

```ts
export default class AuthMiddleware implements Middleware
{
    constructor(role: string, scope: string) { /* store values */ }

    /* handle function */
}
```

Our reflection library can be used for checking the configured arguments and the creation of the instance.

**Comment by BasMasking** [comment]
@petermasking we don't seem to have any validation on the segment file configuration itself at the moment (the reader doesn't check the config). Do we want to add this as well?

**Comment by petermasking** [comment]
The segment file is getting validated at the moment the cache is generated. The runtime only reads the cache segment information, thus can be considered 'correct'. Someone can modify the cache by hand of course, but if I remember correctly, we've decided that's not a high priority yet.

**Comment by petermasking** [comment]
The proposed solution is suitable for cases that require middleware on nodes. Cases that require middleware on multiple services has not been taken in account yet. For example, implementing auth may require authentication on the gateway, and authorization on the node. This means that separate middleware has to be registered in the segment file, and requires the gateway to have all segment information. We need to think this trough before continuing this path.

In the meantime other priorities have come in. Some of these priorities involve the middleware. The branch related to this issue contains major improvements on the middleware implementation that are required to take the next steps. Therefore I've finished the middleware improvements in this branch and created a pull-request. I suggest closing this issue with the middleware improvements and create a new issue for the re-visioned 'middleware per procedure'.
