### ISSUE TITLE
Protect access of 'internal' procedures

### ISSUE THREAD

**Issue by basmasking** [MaskingTechnology/jitar#275]
Some procedures might not be called from outside, but should be accessible internally. The proxy currently passes everything '/rpc/ to the gateway.

Should be able to prevent access to internal procedures.

**Comment by BasMasking** [comment]
If we would take the same approach as with the `assets` in the repository configuration, then we need to add procedures to a whitelist. 

```json
{
    "url": "http://127.0.0.1:8080",
    "proxy":
    {
        "repository": "http://127.0.0.1:2999",
        "gateway": "http://127.0.0.1:3000",
        "procedures": [ "shared/*" ]
    }
}
```

The above configuration should allow all rpc calls to `shared/` to get passed to the gateway.
