### ISSUE TITLE
bug(runtime): handle scenario where two functions are registered as one

### ISSUE THREAD

**Issue by BasMasking** [MaskingTechnology/jitar#300]
When registering functions in segment files a small typo is made easily, especially when using `version`, or when functions are registered with different names using `as`. Jitar doesn't notify the developer that a typo has been made.

The following configurations should not be allowed.

```json
{
    "./shared/sayHello":
    {
        "sayHello": { "access": "public", "version": "1.0.0" }
    },
     "./shared/sayHelloV2":
    {
        "sayHello": { "access": "public", "version": "1.0.0" }
    }
}
```

```json
{
    "./database": {
        "getOrganisation": {
            "as": "getEmployee"
            "access": "public"
        },
        "getEmployee": {
            "as": "getEmployee"
            "access": "public"
        }
    }
}
```

In both cases the first function in the configuration is registered and available as RPC call. The second function is not available.

The expectation would be that this segment configuration is not correct and should throw an error.

**Comment by BasMasking** [comment]
@petermasking I have been looking where we can fix this, but I cannot find any place in the runtime. The RemoteBuilder in the `caching` package seems to output the incorrect data for remote implementations.

```js
// getEmployee.remote.js
export async function getEmployee(id) {
	return __runProcedure('getEmployee', '1.0.0', { 'id': id }, this);
}

export async function getEmployeeV2(uuid) {
	return __runProcedure('getEmployee', '1.0.0', { 'uuid': uuid }, this);
}
```

The local implementation is correct though.

```js
// getEmployee.local.js
export async function getEmployee(id) {
    return {
        id: id,
        name: 'John Doe',
        age: 42,
    };
}
export async function getEmployeeV2(uuid) {
    return {
        uuid: uuid,
        name: 'John Doe',
        age: 42,
        address: '123 Main St.'
    };
}
```

Shall we update the RemoteBuilder to keep track of each fqn and version it has already written for a single module?

**Comment by petermasking** [comment]
We want to avoid finding these kind of issues at the runtime level, so check this while building the cache. Since it's a segment configuration error it should be detected when generating the segment cache model. The `SegmentCacheBuilder` groups the procedures by FQN. At this stage we can detect if a version is registered twice and throw an error.
