### ISSUE TITLE
Add request size limit configuration option

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/jitar#491]
Currently, we can't call remote procedures with a combined parameter size > 100kb. This is enough in most cases, but must be made configurable for all other cases (like Comify).

For the realization we need to dynamically set the limit of of the body parser.

**Comment by basmasking** [comment]
Do we want to have it configurable for each and every route on the server? Or do we only want to have this setting apply to the rpc end point?

**Comment by petermasking** [comment]
I would suggest to start simple by applying it to all PRC calls.

**Comment by basmasking** [comment]
So we don't increase the limit of the body on the health, jitar, etc. endpoints.

Thanks
