### ISSUE TITLE
Fix error deserialization at the gateway

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/jitar#52]
When an error is passed from a node to the gateway, the gateway isn't able to de-serialize the error.

**Reproduction**
This issue can be reproduced by running the segmentation example (only node1 is required). The following request works as expected.

```http
GET http://localhost:3000/rpc/greetings/sayHi?firstName=John
```

When removing the `firstName` parameter from the request, it results into the following error.

```
Module '../..//jitar/core/errors/MissingParameterValue.js' could not be loaded | Cannot find module '/path/to/jitar/examples/1-basic//jitar/core/errors/MissingParameterValue.js' imported from /path/to/jitar/examples/1-basic/2-segmentation/dist/start.js
```

The expected result is as follows.

```
Missing value for parameter 'firstName'
```

**Comment by BasMasking** [comment]
As discussed we use CLIENT_0 as the client id for getting the moduleLocation. The id is not registered at the time of retrieval, but that doens't matter for the api call to succeed.


We might have found an issue. The moduleLocation can be called by anyone, as the repository currently doesn't look at the id of the client. Do we want to add an enhancement to only provide the location in case the client is registered? That would mean rework on this solution, but what would the security gain be? Only the location of the repository, that is already known when it's called.

**Comment by petermasking** [comment]
The issue that I see with this approach is that we have no control over the content of CLIENT_0 because it depends on the registered segments of the first node. Is this a problem? Not in theory. Segments _should_ only contain procedures, not data models. The gateway only needs the repository for getting the data models to be able to de-serialize them. So there _should_ be no conflicts.

That said, this isn't a solid solution yet. I suggest that we register the gateway at the repository as a normal client without any segments. This ensures an unique client id that isn't bound to any content.

**Comment by BasMasking** [comment]
The gateway now registers itself as a client with the repository.
