### ISSUE TITLE
Data type validation on RPC calls

### ISSUE THREAD

**Issue by basmasking** [MaskingTechnology/jitar#61]
Jitar needs to have an option to validate incoming data through its apis. As with the rest of the product, we want to have a configuration only option to define the validation schemas.

What needs to be done for this story;
- update the segment file configuration with a validation model
- add the configuration to generated cache files
- validate the incoming data on the server with the provided configuration
- translate validation errors to http 400

**Comment by BasMasking** [comment]
After we have investigated the issue and setup a first version, we found out that there is a large amount of work to be done for this story.

There are more urgent issues to pick up, as the validation can also be done by an application using excellent libraries available.

**Comment by BasMasking** [comment]
@petermasking are we planning to use a zod ovject for this?

**Comment by basmasking** [comment]
We close this issue because we have changed our strategy regarding the validation of incoming requests. The data should be validated in the applicaiton code to make it easier to move away from jitar without the need for rebuilding the validation elsewhere.
